[package]
name = "cja"
description = "Cron, Jobs and Axum a meta-framework for building web applications"
authors = ["Corey Alexander"]
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
