use std::error::Error;

use vergen::EmitBuilder;

// generated by `sqlx migrate build-script`
fn main() -> Result<(), Box<dyn Error>> {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    EmitBuilder::builder().all_git().emit()?;

    Ok(())
}
