name: Approve and Auto-merge Screenshot PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    # Only run this job if the PR was created by the GitHub Actions bot and has "Update Daily Screenshot" in the title
    if: github.event.pull_request.user.login == 'github-actions[bot]' && contains(github.event.pull_request.title, 'Update Daily Screenshot')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Approve Pull Request
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-merge
        run: |
          gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
