name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-tests:
    name: Frontend Tests
    uses: ./.github/workflows/frontend-tests-reusable.yml

  rust-tests:
    name: Rust Tests
    uses: ./.github/workflows/rust-tests-reusable.yml

  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    needs: [frontend-tests, rust-tests]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}