name: Playwright Tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        type: string
        default: 'test'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/coreyja_test
  APP_BASE_URL: http://localhost:3000
  SQLX_OFFLINE: true
  # Required environment variables for app startup (using test/fake values)
  OPEN_AI_API_KEY: test-openai-api-key
  ANTHROPIC_API_KEY: test-anthropic-api-key
  GITHUB_APP_ID: 123456
  GITHUB_APP_CLIENT_ID: test-github-client-id
  GITHUB_APP_CLIENT_SECRET: test-github-client-secret
  GITHUB_PERSONAL_ACCESS_TOKEN: test-github-pat
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0Z3VS0JJcds3xg
    -----END RSA PRIVATE KEY-----
  TWITCH_CLIENT_ID: test-twitch-client-id
  TWITCH_CLIENT_SECRET: test-twitch-client-secret
  TWITCH_BOT_USER_ID: 123456789
  TWITCH_CHANNEL_USER_ID: 987654321
  ENCRYPTION_SECRET_KEY: test-encryption-secret-key-32-bytes-long!
  GOOGLE_CLIENT_ID: test-google-client-id
  GOOGLE_CLIENT_SECRET: test-google-client-secret
  DISCORD_TOKEN: test-discord-token
  DISCORD_BOT_DISABLED: true
  COOKIE_KEY: test-cookie-key-32-bytes-long!!!!

jobs:
  playwright:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: coreyja_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            thread-frontend/package-lock.json
            e2e/package-lock.json
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler libasound2-dev
          version: v0
      
      - name: Install Tailwind CSS
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 && \
          chmod +x tailwindcss-linux-x64 && \
          mv tailwindcss-linux-x64 tailwindcss && \
          ./tailwindcss -i server/src/styles/tailwind.css -o target/tailwind.css
      
      - name: Install frontend dependencies
        run: |
          cd thread-frontend
          npm ci
      
      - name: Build frontend
        run: ./scripts/build-frontend.sh
      
      - name: Run database migrations
        run: |
          cargo install sqlx-cli --no-default-features --features postgres || true
          sqlx migrate run --source db/migrations
      
      - name: Build server (debug mode for speed)
        run: cargo build --bin server
      
      - name: Install Playwright dependencies
        run: |
          cd e2e
          npm ci
      
      - name: Install Playwright browsers
        run: |
          cd e2e
          npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        run: |
          cd e2e
          npx playwright test
        env:
          CI: true
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: e2e/test-results/
          retention-days: 30