name: Take screenshots

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write
  id-token: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      pr_number: ${{ steps.create-pr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers
      - name: Cache OxiPNG
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo
      - name: Install dependencies
        run: |
          pip install shot-scraper
          which oxipng || cargo install oxipng
          shot-scraper install
      - name: Take retina shots
        run: |
          shot-scraper multi live.shots.yml --retina
      - name: Optimize PNGs
        run: |-
          oxipng -o 4 -i 0 --strip safe screenshots/*.png
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - run: git checkout -b update-screenshot-${{ steps.date.outputs.date }}
      - run: git push --set-upstream origin update-screenshot-${{ steps.date.outputs.date }}
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)
      - name: Make PR
        run: |
          curl -X POST https://workflow-automation.fly.dev/create-pr \
            -H "Content-Type: application/json" \
            -d '{"github_oidc_jwt": "${{ steps.idtoken.outputs.id_token }}", "owner": "coreyja", "repo": "coreyja.com", "base_branch": "main", "head_branch": "update-screenshot-${{ steps.date.outputs.date }}", "title": "Update Daily Screenshot -- ${{ steps.date.outputs.date }}", "body": "Automated daily screenshot update for ${{ steps.date.outputs.date }}"}'
