name: Take screenshots

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      pr_number: ${{ steps.create-pr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers
      - name: Cache OxiPNG
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo
      - name: Install dependencies
        run: |
          pip install shot-scraper
          which oxipng || cargo install oxipng
          shot-scraper install
      - name: Take retina shots
        run: |
          shot-scraper multi live.shots.yml --retina
      - name: Optimize PNGs
        run: |-
          oxipng -o 4 -i 0 --strip safe screenshots/*.png
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update screenshot for ${{ steps.date.outputs.date }}
          title: "Update Daily Screenshot -- ${{ steps.date.outputs.date }}"
          body: "Automated daily screenshot update for ${{ steps.date.outputs.date }}"
          branch: update-screenshot
          branch-suffix: timestamp
          base: main

  approve-and-merge:
    runs-on: ubuntu-latest
    needs: shot-scraper
    env:
      PR_NUMBER: ${{ needs.shot-scraper.outputs.pr_number }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Auto-merge
        run: |
          gh pr merge --auto --squash "$PR_NUMBER"
